name: remote ssh command for deploy
on:
  push: #푸시 이벤트가 일어날 때
    branches: [master]
jobs: #jobs 에 관련된 사항을 실행
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master #github 마켓플레이스에서 이 템플릿을 사용
        with: # 환경변수
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #pem 키 내용 확인 필요
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          #홈디렉토리의 deploy.sh 파일 실행
          script: |
            ./deploy.sh
